# Generated by Django 2.2 on 2019-09-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='title',
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(default='email', max_length=30, verbose_name='Mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('blocked', 'Заблокировано')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
